version: '3.8'

services:
  app :
    build: .
    volumes:
      - .:/app
    tty: true
    restart: always
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    tty: true
    restart: always
